"""gmail_manager.py — Gmail label management + IMAP job storage via App Password"""
import imaplib
import smtplib
import email
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.header import decode_header
import re
from datetime import datetime

try:
    from config import EMAIL_USER, EMAIL_PASS
except Exception:
    EMAIL_USER = ""
    EMAIL_PASS = ""

LABEL_JOBS        = "Job-AI/All-Jobs"
LABEL_APPLIED     = "Job-AI/Applied"
LABEL_SHORTLISTED = "Job-AI/Shortlisted"
LABEL_GENERATED   = "Job-AI/Generated-Resumes"


# ── IMAP helpers ──────────────────────────────────────────────────────────────

def _connect_imap():
    imap = imaplib.IMAP4_SSL("imap.gmail.com")
    imap.login(EMAIL_USER, EMAIL_PASS)
    return imap


def _label_exists(imap, label):
    status, mailboxes = imap.list()
    if status != "OK":
        return False
    for mb in mailboxes:
        if mb and label.lower() in mb.decode(errors="ignore").lower():
            return True
    return False


def create_labels():
    """Create all Job-AI Gmail labels (folders) if they don't exist yet."""
    if not EMAIL_USER or not EMAIL_PASS:
        print("  Gmail credentials not configured — skipping label creation.")
        return False
    try:
        imap = _connect_imap()
        for label in [LABEL_JOBS, LABEL_APPLIED, LABEL_SHORTLISTED, LABEL_GENERATED]:
            if not _label_exists(imap, label):
                imap.create(f'"{label}"')
                print(f"  Created Gmail label: {label}")
            else:
                print(f"  Label exists: {label}")
        imap.logout()
        return True
    except Exception as exc:
        print(f"  Gmail label setup failed: {exc}")
        return False


# ── SMTP helpers ──────────────────────────────────────────────────────────────

def _send_to_label(subject: str, html_body: str, label: str):
    """Send an email to yourself that Gmail will auto-label via a filter,
    and also manually move it via IMAP append."""
    msg = MIMEMultipart("alternative")
    msg["From"]    = EMAIL_USER
    msg["To"]      = EMAIL_USER
    msg["Subject"] = f"[{label}] {subject}"
    msg["X-Job-AI-Label"] = label
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP("smtp.gmail.com", 587) as srv:
        srv.starttls()
        srv.login(EMAIL_USER, EMAIL_PASS)
        srv.send_message(msg)


def store_jobs_in_gmail(jobs: list):
    """Email a summary of fetched jobs to yourself and file under Job-AI/All-Jobs."""
    if not jobs:
        return
    if not EMAIL_USER or not EMAIL_PASS:
        print("  Gmail credentials not configured — skipping email storage.")
        return

    rows = ""
    for j in jobs[:20]:
        ats_color = "#27ae60" if j.get("ats", 0) >= 85 else "#f39c12" if j.get("ats", 0) >= 75 else "#e74c3c"
        rows += f"""
        <tr>
          <td style="padding:8px;border-bottom:1px solid #eee">{j.get('title','')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee">{j.get('company','')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee">{j.get('location','')}</td>
          <td style="padding:8px;border-bottom:1px solid #eee;font-weight:bold;color:{ats_color}">{j.get('ats','N/A')}%</td>
          <td style="padding:8px;border-bottom:1px solid #eee"><a href="{j.get('url','#')}">Apply</a></td>
        </tr>"""

    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333">
      <h2 style="color:#2c3e50">Job-AI — New Jobs Found</h2>
      <p><strong>Date:</strong> {datetime.now().strftime('%B %d, %Y %H:%M')}</p>
      <p><strong>Total jobs:</strong> {len(jobs)}</p>
      <table style="border-collapse:collapse;width:100%">
        <thead>
          <tr style="background:#2c3e50;color:white">
            <th style="padding:10px">Title</th><th style="padding:10px">Company</th>
            <th style="padding:10px">Location</th><th style="padding:10px">ATS</th>
            <th style="padding:10px">Link</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="color:#888;font-size:12px">Generated by Job-AI Resume Optimizer</p>
    </body></html>"""

    try:
        _send_to_label(f"Job Digest — {datetime.now().strftime('%Y-%m-%d')} ({len(jobs)} jobs)", html, LABEL_JOBS)
        print(f"  Job digest emailed → Gmail label: {LABEL_JOBS}")
    except Exception as exc:
        print(f"  Could not email job digest: {exc}")


def store_resume_in_gmail(job: dict, resume_text: str, ats_score: float):
    """Email a generated resume summary to Gmail under Job-AI/Generated-Resumes."""
    if not EMAIL_USER or not EMAIL_PASS:
        return

    html = f"""
    <html><body style="font-family:Arial,sans-serif;color:#333">
      <h2 style="color:#2c3e50">Resume Generated — {job.get('title','')} @ {job.get('company','')}</h2>
      <p><strong>ATS Score:</strong> <span style="font-size:1.4em;font-weight:bold;color:#27ae60">{ats_score}%</span></p>
      <p><strong>Location:</strong> {job.get('location','')}</p>
      <p><strong>Source:</strong> {job.get('source','')}</p>
      <p><strong>Job URL:</strong> <a href="{job.get('url','#')}">{job.get('url','')}</a></p>
      <hr>
      <h3>Resume Content</h3>
      <pre style="background:#f5f5f5;padding:15px;border-radius:4px;white-space:pre-wrap">{resume_text}</pre>
      <p style="color:#888;font-size:12px">Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}</p>
    </body></html>"""

    try:
        _send_to_label(
            f"Resume: {job.get('title','')} @ {job.get('company','')} — ATS {ats_score}%",
            html,
            LABEL_GENERATED,
        )
    except Exception as exc:
        print(f"  Could not store resume in Gmail: {exc}")


def list_gmail_jobs(label: str = LABEL_JOBS, max_results: int = 10):
    """List subject lines of emails in a Job-AI Gmail label."""
    if not EMAIL_USER or not EMAIL_PASS:
        print("  Gmail credentials not configured.")
        return []
    try:
        imap = _connect_imap()
        imap.select(f'"{label}"')
        status, data = imap.search(None, "ALL")
        if status != "OK" or not data[0]:
            imap.logout()
            return []
        ids = data[0].split()[-max_results:]
        results = []
        for msg_id in reversed(ids):
            status2, msg_data = imap.fetch(msg_id, "(RFC822.SIZE BODY[HEADER.FIELDS (SUBJECT DATE)])")
            if status2 == "OK":
                raw_header = msg_data[0][1].decode(errors="ignore")
                subj_match = re.search(r"Subject: (.+)", raw_header)
                date_match = re.search(r"Date: (.+)", raw_header)
                results.append({
                    "subject": subj_match.group(1).strip() if subj_match else "No subject",
                    "date": date_match.group(1).strip() if date_match else "",
                })
        imap.logout()
        return results
    except Exception as exc:
        print(f"  IMAP error: {exc}")
        return []


def mark_job_applied(job: dict):
    """Send a quick 'applied' confirmation email filed under Job-AI/Applied."""
    if not EMAIL_USER or not EMAIL_PASS:
        return
    html = f"""
    <html><body style="font-family:Arial,sans-serif">
      <h2 style="color:#27ae60">Applied! — {job.get('title','')} @ {job.get('company','')}</h2>
      <p><strong>Date Applied:</strong> {datetime.now().strftime('%B %d, %Y')}</p>
      <p><strong>Location:</strong> {job.get('location','')}</p>
      <p><strong>ATS Score:</strong> {job.get('ats','N/A')}%</p>
      <p><a href="{job.get('url','#')}">Job Link</a></p>
    </body></html>"""
    try:
        _send_to_label(f"Applied: {job.get('title','')} @ {job.get('company','')}", html, LABEL_APPLIED)
        print(f"  Marked as applied → Gmail label: {LABEL_APPLIED}")
    except Exception as exc:
        print(f"  Could not mark as applied: {exc}")
